name: EnvVar
'on': [push, workflow_dispatch]      
jobs: 
  Infojob:
      runs-on: ubuntu-latest
      steps:
        - name: Step 1
          run: |
            echo "${{ toJSON(github) }}"
            echo "${{ github.workflow }}"
            echo "${{ github.job }}"
