name: EnvVar
'on': [push, workflow_dispatch]      
jobs: 
    
  Infojob:
      runs-on: ubuntu-latest
      outputs:
        script-file: ${{ steps.publish.ouputs.script-file }}
      steps:
        - name: Step 1
          run: |
            echo "${{ toJSON(github) }}"
            echo "${{ github.workflow }}"
            echo "${{ github.job }}"
        - name: Zip files
          uses: OctopusDeploy/create-zip-package-action@v3
          with:
            package_id: demo.md
            version: 1
            output_folder: './'
            base_path: ./
            files: |
              demo.md              
        - name: Publish filename
          id: publish
          run: find ./*.md -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
