name: EnvVar
'on':
  push:
    branches:
      -'main'
  workflow_dispatch:
      
jobs: 
  Infojob:
      runs-on: ubuntu-latest
      steps:
        - name: Step 1
          run: echo "${{ toJSON(github) }}"
