name: My First Action
'on': [workflow_dispatch]

jobs:
  job1:
    name: Get machine info
    runs-on: windows-latest
    steps:
      - name: Step 1
        run: hostname
      - name: Step 2
        run: ipconfig
      
  job2:
    name: Get machine info 2
    runs-on: windows-latest
    steps:
      - name: Step 1
        run: |
          hostname
          ipconfig /all
    
