name: My Second Action
'on': [push, workflow_dispatch]

jobs:
  job1:
    name: Get machine info
    runs-on: windows-latest
    steps:
      - name: Step 1
        run: hostname
      
  job2:
    info:
      runs-on: windows-latest
      steps:
        - name: Step 1
          run: echo "${{ toJSON(github) }}"

